# Generated by Django 5.2.3 on 2025-06-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Discussions'},
        ),
        migrations.AddField(
            model_name='discussion',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
